### ISSUE TITLE
Add support for Charm mod

### ISSUE THREAD

**Issue by mrmelon54** [MrMelon54/better-christmas-chests-fabric#1]

**Comment by DaveyL2013** [comment]
I think you missed the chest boats lol

https://user-images.githubusercontent.com/20153257/185246360-131c9fa1-d824-4f63-bc90-2871effce47b.mp4

**Comment by mrmelon54** [comment]
video doesn't play lol

**Comment by DaveyL2013** [comment]
huh i guess apparently chrome doesn't support h265 encoding despite the video playing perfectly fine when downloaded
good to know

**Comment by mrmelon54** [comment]
I use firefox anyway lol
Can you send the video again

**Comment by mrmelon54** [comment]
Moved to https://github.com/mrmelon54/better_christmas_chests/issues/1
