### ISSUE TITLE
Mod Menu Dependency Error

### ISSUE THREAD

**Issue by Lukebb04** [MrMelon54/better-christmas-chests-fabric#3]
Allow the game to be open with [catalogue](https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric) with [menulogue](https://www.curseforge.com/minecraft/mc-mods/menulogue) insted of mod menu

**Comment by mrmelon54** [comment]
I'm not stopping you open the game with catalogue and menulogue?

I don't exactly understand what you are asking for?

**Comment by Lukebb04** [comment]
mod menu is in the dependency list [here](https://github.com/MrMelon54/better-christmas-chests-fabric/blob/9d699746217e01feb0440848efa8ddbb7609e0fc/src/main/resources/fabric.mod.json#L33)

**Comment by mrmelon54** [comment]
Fixed in e64d7f1769bba999a967555823ec3a2cb3f44255, coming in next release
