### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by slushie0** [MrMelon54/better-christmas-chests-fabric#4]

**Comment by tabbeddev** [comment]
Do you mean by that, that the 1.19.2 Version also works with the 1.19.3?

**Comment by mrmelon54** [comment]
> Do you mean by that, that the 1.19.2 Version also works with the 1.19.3?

you could try it and see.. if it doesn't then provide a crash report or log

**Comment by tabbeddev** [comment]
I have tried it. And its works!

**Comment by mrmelon54** [comment]
> I have tried it. And its works!

then I probably not need to add 1.19.3 version numbers on the download pages

**Comment by slushie0** [comment]
Oh, good. I thought that a mod built for 1.19.2 wouldn't work for any other version regardless, I thought fabric didn't allow it.

**Comment by slushie0** [comment]
Although, for software that automatically downloads mods, it won't download it because it thinks it's not compatible. (And some people might not be aware)

So, If you could update the versions somehow or just re upload it for 1.19.3, that would be nice.

**Comment by mrmelon54** [comment]
oh I usually compile mods with version "1.19.x" and then update the version numbers on the download website

I've done that as this mod works fine 👍
