### ISSUE TITLE
Large trapped chest texture is glitched

### ISSUE THREAD

**Issue by bwilliance** [MrMelon54/better-christmas-chests-fabric#6]
The Christmas chest texture for the double trapped chest is glitched
![2023-08-18_04 09 52](https://github.com/MrMelon54/better-christmas-chests-fabric/assets/97874863/1d21609d-f1e3-421f-ba76-68303f29ef81)

**Comment by mrmelon54** [comment]
Can I have the following information:

MC version
Better Christmas Chests version
Any other mods you have loaded (don't need specific versions)

**Comment by bwilliance** [comment]
Minecraft version: 1.20.1
Quilt loader version: 0.19.4
Better Christmas Chests version: better_christmas_chests-mc1.20-1.0.0-build.5
Other mods: Mod Menu, Quilted Fabric API, Quilt Kotlin Libraries, Architectury API, and Cloth Config

**Comment by mrmelon54** [comment]
Report on https://github.com/mrmelon54/better_christmas_chests if this issue still occurs
